// Types of client 
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";

export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
export const GET_CLIENT_FAILED = "GET_CLIENT_FAILED";

export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_FAILED = "UPDATE_CLIENT_FAILED";

export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";

//Types of commandeVente
export const ADD_COMMANDEVENTE_SUCCESS = "ADD_COMMANDEVENTE_SUCCESS";
export const ADD_COMMANDEVENTE_FAILED = "ADD_COMMANDEVENTE_FAILED";

export const GET_COMMANDEVENTE_SUCCESS = "GET_COMMANDEVENTE_SUCCESS";
export const GET_COMMANDEVENTE_FAILED = "GET_COMMANDEVENTE_FAILED";

export const UPDATE_COMMANDEVENTE_SUCCESS = "UPDATE_COMMANDEVENTE_SUCCESS";
export const UPDATE_COMMANDEVENTE_FAILED = "UPDATE_COMMANDEVENTE_FAILED";

export const DELETE_COMMANDEVENTE_SUCCESS = "DELETE_COMMANDEVENTE_SUCCESS";
export const DELETE_COMMANDEVENTE_FAILED = "DELETE_COMMANDEVENTE_FAILED";

//Types of contact
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED";

export const GET_CONTACT_SUCCESS = "GET_CONTACT_SUCCESS";
export const GET_CONTACT_FAILED = "GET_CONTACT_FAILED";

export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAILED = "UPDATE_CONTACT_FAILED";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED";

//Types of entreprise
export const ADD_ENTREPRISE_SUCCESS = "ADD_ENTREPRISE_SUCCESS";
export const ADD_ENTREPRISE_FAILED = "ADD_ENTREPRISE_FAILED";

export const GET_ENTREPRISE_SUCCESS = "GET_ENTREPRISE_SUCCESS";
export const GET_ENTREPRISE_FAILED = "GET_ENTREPRISE_FAILED";

export const UPDATE_ENTREPRISE_SUCCESS = "UPDATE_ENTREPRISE_SUCCESS";
export const UPDATE_ENTREPRISE_FAILED = "UPDATE_ENTREPRISE_FAILED";

export const DELETE_ENTREPRISE_SUCCESS = "DELETE_ENTREPRISE_SUCCESS";
export const DELETE_ENTREPRISE_FAILED = "DELETE_ENTREPRISE_FAILED";

//Types of lignereservation
export const ADD_LIGNERESERVATION_SUCCESS = "ADD_LIGNERESERVATION_SUCCESS";
export const ADD_LIGNERESERVATION_FAILED = "ADD_LIGNERESERVATION_FAILED";

export const GET_LIGNERESERVATION_SUCCESS = "GET_LIGNERESERVATION_SUCCESS";
export const GET_LIGNERESERVATION_FAILED = "GET_LIGNERESERVATION_FAILED";

export const UPDATE_LIGNERESERVATION_SUCCESS = "UPDATE_LIGNERESERVATION_SUCCESS";
export const UPDATE_LIGNERESERVATION_FAILED = "UPDATE_LIGNERESERVATION_FAILED";

export const DELETE_LIGNERESERVATION_SUCCESS = "DELETE_LIGNERESERVATION_SUCCESS";
export const DELETE_LIGNERESERVATION_FAILED = "DELETE_LIGNERESERVATION_FAILED";

//Types of ligneVente
export const ADD_LIGNEVENTE_SUCCESS = "ADD_LIGNEVENTE_SUCCESS";
export const ADD_LIGNEVENTE_FAILED = "ADD_LIGNEVENTE_FAILED";

export const GET_LIGNEVENTE_SUCCESS = "GET_LIGNEVENTE_SUCCESS";
export const GET_LIGNEVENTE_FAILED = "GET_LIGNEVENTE_FAILED";

export const UPDATE_LIGNEVENTE_SUCCESS = "UPDATE_LIGNEVENTE_SUCCESS";
export const UPDATE_LIGNEVENTE_FAILED = "UPDATE_LIGNEVENTE_FAILED";

export const DELETE_LIGNEVENTE_SUCCESS = "DELETE_LIGNEVENTE_SUCCESS";
export const DELETE_LIGNEVENTE_FAILED = "DELETE_LIGNEVENTE_FAILED";

//Types of reservation
export const ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS";
export const ADD_RESERVATION_FAILED = "ADD_RESERVATION_FAILED";

export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS";
export const GET_RESERVATION_FAILED = "GET_RESERVATION_FAILED";

export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_FAILED = "UPDATE_RESERVATION_FAILED";

export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_FAILED = "DELETE_RESERVATION_FAILED";

//Types of tva
export const ADD_TVA_SUCCESS = "ADD_TVA_SUCCESS";
export const ADD_TVA_FAILED = "ADD_TVA_FAILED";

export const GET_TVA_SUCCESS = "GET_TVA_SUCCESS";
export const GET_TVA_FAILED = "GET_TVA_FAILED";

export const UPDATE_TVA_SUCCESS = "UPDATE_TVA_SUCCESS";
export const UPDATE_TVA_FAILED = "UPDATE_TVA_FAILED";

export const DELETE_TVA_SUCCESS = "DELETE_TVA_SUCCESS";
export const DELETE_TVA_FAILED = "DELETE_TVA_FAILED";





