export const LOAD_PERSONNEL_SUCCESS = "LOAD_PERSONNEL_SUCCESS";
export const LOAD_PERSONNEL_FAILED = "LOAD_PERSONNEL_FAILED";

export const ADD_PERSONNEL_SUCCESS = "ADD_PERSONNEL_SUCCESS";
export const ADD_PERSONNEL_FAILED = "ADD_PERSONNEL_FAILED";
export const EDIT_PERSONNEL_SUCCESS="EDIT_PERSONNEL_SUCCESS";
export const EDIT_PERSONNEL_FAILED="EDIT_PERSONNEL_FAILED";
export const DELETE_PERSONNEL_SUCCESS="DELETE_PERSONNEL_SUCCESS";
export const DELETE_PERSONNEL_FAILED ="DELETE_PERSONNEL_FAILED"