export const LOAD_PERSONNEL_SUCCESS = "LOAD_PERSONNEL_SUCCESS";
export const LOAD_PERSONNEL_FAILED = "LOAD_PERSONNEL_FAILED";

export const ADD_PERSONNEL_SUCCESS = "ADD_PERSONNEL_SUCCESS";
export const ADD_PERSONNEL_FAILED = "ADD_PERSONNEL_FAILED";

export const EDIT_PERSONNEL_SUCCESS="EDIT_PERSONNEL_SUCCESS";
export const EDIT_PERSONNEL_FAILED="EDIT_PERSONNEL_FAILED";

export const DELETE_PERSONNEL_SUCCESS="DELETE_PERSONNEL_SUCCESS";
export const DELETE_PERSONNEL_FAILED ="DELETE_PERSONNEL_FAILED"

// TYPES OF CONTRAT 
export const LOAD_CONTRAT_SUCCESS= "LOAD_CONTRAT_SUCCESS";
export const LOAD_CONTRAT_FAILED = "LOAD_CONTRAT_FAILED";

export const ADD_CONTRAT_SUCCESS = "ADD_CONTRAT_SUCCESS";
export const ADD_CONTRAT_FAILED = "ADD_CONTRAT_FAILED";

export const EDIT_CONTRAT_SUCCESS = "EDIT_CONTRAT_SUCCESS";
export const EDIT_CONTRAT_FAILED = "EDIT_CONTRAT_FAILED";

export const DELETE_CONTRAT_SUCCESS = "DELETE_CONTRAT_SUCCESS";
export const DELETE_CONTRAT_FAILED = "DELETE_CONTRAT_FAILED";

// TYPES OF SERVICE
export const ADD_SERVICE_SUCCESS ="ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAILED = "ADD_SERVICE_FAILED";

export const LOAD_SERVICE_SUCCESS = "LOAD_SERVICE_SUCCESS";
export const LOAD_SERVICE_FAILED = "LOAD_SERVICE_FAILED";

export const EDIT_SERVICE_SUCCESS = "EDIT_SERVICE_SUCCESS";
export const EDIT_SERVICE_FAILED = "EDIT_SERVICE_FAILED";

export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAILED = "DELETE_SERVICE_FAILED"

// TYPES OF EMBAUCHE
export const ADD_EMBAUCHE_SUCCESS = 'ADD_EMBAUCHE_SUCCESS';
export const ADD_EMBAUCHE_FAILED = 'ADD_EMBAUCHE_FAILED';

export const LOAD_EMBAUCHE_SUCCESS = 'LOAD_EMBAUCHE_SUCCESS';
export const LOAD_EMBAUCHE_FAILED = 'LOAD_EMBAUCHE_FAILED';

export const DELETE_EMBAUCHE_SUCCESS = 'DELETE_EMBAUCHE_SUCCESS';
export const DELETE_EMBAUCHE_FAILED = 'DELETE_EMBAUCHE_FAILED'
