export const LOAD_PERSONNEL_SUCCESS = "LOAD_PERSONNEL_SUCCESS";
export const LOAD_PERSONNEL_FAILED = "LOAD_PERSONNEL_FAILED";

export const ADD_PERSONNEL_SUCCESS = "ADD_PERSONNEL_SUCCESS";
export const ADD_PERSONNEL_FAILED = "ADD_PERSONNEL_FAILED";
