// Types of caregorie
export const ADD_CATEGORIE_SUCCESS = "ADD_CATEGORIE_SUCCESS";
export const ADD_CATEGORIE_FAILED = "ADD_CATEGORIE_FAILED";
export const GET_CATEGORIE_SUCCESS = "GET_CATEGORIE_SUCCESS";
export const GET_CATEGORIE_FAILED = "GET_CATEGORIE_FAILED";

// Types of commande Achat
export const ADD_COMMANDEACHAT_SUCCESS = "ADD_COMMANDEACHAT_SUCCESS";
export const ADD_COMMANDEACHAT_FAILED = "ADD_COMMANDEACHAT_FAILED";
export const GET_COMMANDEACHAT_SUCCESS = "GET_COMMANDEACHAT_SUCCESS";
export const GET_COMMANDEACHAT_FAILED = "GET_COMMANDEACHAT_FAILED";
export const UPDATE_COMMANDEACHAT_SUCCESS = "UPDATE_COMMANDEACHAT_SUCCESS";
export const UPDATE_COMMANDEACHAT_FAILED = "UPDATE_COMMANDEACHAT_FAILED";
export const DELETE_COMMANDEACHAT_SUCCESS = "DELETE_COMMANDEACHAT_SUCCESS";
export const DELETE_COMMANDEACHAT_FAILED = "DELETE_COMMANDEACHAT_FAILED";

// Types of compte Bancaire
export const ADD_COMPTEBANCAIRE_SUCCESS = "ADD_COMPTEBANCAIRE_SUCCESS";
export const ADD_COMPTEBANCAIRE_FAILED = "ADD_COMPTEBANCAIRE_FAILED";
export const GET_COMPTEBANCAIRE_SUCCESS = "GET_COMPTEBANCAIRE_SUCCESS";
export const GET_COMPTEBANCAIRE_FAILED = "GET_COMPTEBANCAIRE_FAILED";
export const UPDATE_COMPTEBANCAIRE_SUCCESS = "UPDATE_COMPTEBANCAIRE_SUCCESS";
export const UPDATE_COMPTEBANCAIRE_FAILED = "UPDATE_COMPTEBANCAIRE_FAILED";
export const DELETE_COMPTEBANCAIRE_SUCCESS = "DELETE_COMPTEBANCAIRE_SUCCESS";
export const DELETE_COMPTEBANCAIRE_FAILED = "DELETE_COMPTEBANCAIRE_FAILED";

// Types of facture
export const ADD_FACTURE_SUCCESS = "ADD_FACTURE_SUCCESS";
export const ADD_FACTURE_FAILED = "ADD_FACTURE_FAILED";
export const GET_FACTURE_SUCCESS = "GET_FACTURE_SUCCESS";
export const GET_FACTURE_FAILED = "GET_FACTURE_FAILED";
export const UPDATE_FACTURE_SUCCESS = "UPDATE_FACTURE_SUCCESS";
export const UPDATE_FACTURE_FAILED = "UPDATE_FACTURE_FAILED";
export const DELETE_FACTURE_SUCCESS = "DELETE_FACTURE_SUCCESS";
export const DELETE_FACTURE_FAILED = "DELETE_FACTURE_FAILED";

// Types of produit
export const ADD_PRODUIT_SUCCESS = "ADD_PRODUIT_SUCCESS";
export const ADD_PRODUIT_FAILED = "ADD_PRODUIT_FAILED";
export const GET_PRODUIT_SUCCESS = "GET_PRODUIT_SUCCESS";
export const GET_PRODUIT_FAILED = "GET_PRODUIT_FAILED";
export const UPDATE_PRODUIT_SUCCESS = "UPDATE_PRODUIT_SUCCESS";
export const UPDATE_PRODUIT_FAILED = "UPDATE_PRODUIT_FAILED";
export const DELETE_PRODUIT_SUCCESS = "DELETE_PRODUIT_SUCCESS";
export const DELETE_PRODUIT_FAILED = "DELETE_PRODUIT_FAILED";