// Types of caregorie
export const ADD_CATEGORIE_SUCCESS = "ADD_CATEGORIE_SUCCESS";
export const ADD_CATEGORIE_FAILED = "ADD_CATEGORIE_FAILED";
export const GET_CATEGORIE_SUCCESS = "GET_CATEGORIE_SUCCESS";
export const GET_CATEGORIE_FAILED = "GET_CATEGORIE_FAILED";

// Types of commande Achat
export const ADD_COMMANDEACHAT_SUCCESS = "ADD_COMMANDEACHAT_SUCCESS";
export const ADD_COMMANDEACHAT_FAILED = "ADD_COMMANDEACHAT_FAILED";
export const GET_COMMANDEACHAT_SUCCESS = "GET_COMMANDEACHAT_SUCCESS";
export const GET_COMMANDEACHAT_FAILED = "GET_COMMANDEACHAT_FAILED";
export const UPDATE_COMMANDEACHAT_SUCCESS = "UPDATE_COMMANDEACHAT_SUCCESS";
export const UPDATE_COMMANDEACHAT_FAILED = "UPDATE_COMMANDEACHAT_FAILED";
export const DELETE_COMMANDEACHAT_SUCCESS = "DELETE_COMMANDEACHAT_SUCCESS";
export const DELETE_COMMANDEACHAT_FAILED = "DELETE_COMMANDEACHAT_FAILED";