// Types of caregorie
export const ADD_CATEGORIE_SUCCESS = "ADD_CATEGORIE_SUCCESS";
export const ADD_CATEGORIE_FAILED = "ADD_CATEGORIE_FAILED";
export const GET_CATEGORIE_SUCCESS = "GET_CATEGORIE_SUCCESS";
export const GET_CATEGORIE_FAILED = "GET_CATEGORIE_FAILED";

